# Generated by Django 4.2.7 on 2023-11-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=191)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('password', models.CharField(max_length=191)),
                ('accountType', models.CharField(max_length=191)),
                ('userID', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'userB',
            },
        ),
    ]
