# Generated by Django 4.2.7 on 2023-11-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0002_carmodel_reservation_features_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='2001-08-11'),
        ),
    ]
