# Generated by Django 4.2.7 on 2023-11-27 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0005_alter_vehicle_price_alter_vehicle_table_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
