# Generated by Django 4.2.7 on 2023-11-28 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0006_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('year', models.CharField(default='YYYY', max_length=4)),
                ('price', models.DecimalField(default=0.0, decimal_places=2, max_digits=12)),
                ('available_from_date', models.DateField(default=None, null=True)),
                ('available_to_date', models.DateField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(choices=[('Dublin', 'Dublin'), ('Cork', 'Cork'), ('Limerick', 'Limerick')], default=None, max_length=20, null=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]